export enum ActionType {
  BUTTON_SELECTION = "BUTTON_SELECTION",
  GET_TRENDING_MOVIES_IDS = "GET_TRENDING_MOVIES_IDS",
  GET_POPULAR_MOVIES_IDS = "GET_POPULAR_MOVIES_IDS",
  GET_RECOMMENDED_MOVIES_IDS = "GET_RECOMMENDED_MOVIES_IDS",
  GET_RECOMMENDED_MOVIES_DATA = "GET_RECOMMENDED_MOVIES_DATA",
  GET_POPULAR_MOVIES_DATA = "GET_POPULAR_MOVIES_DATA",
  GET_TRENDING_MOVIES_DATA = "GET_TRENDING_MOVIES_DATA",
}
